[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.21.3"
regex = "1.11.1"
pwshare-macros = { path = "pwshare-macros" }
rand = "0.10.1"
num-traits = "0.2.19"
crypto-bigint = { version = "0.7.3", features = ["alloc", "rand_core"] }
dudect-bencher = "0.7.0"

[profile.release]
debug = 1
